// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: configure_resource_server.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllResourceServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId uint32 `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
}

func (x *AllResourceServerRequest) Reset() {
	*x = AllResourceServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configure_resource_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllResourceServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllResourceServerRequest) ProtoMessage() {}

func (x *AllResourceServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configure_resource_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllResourceServerRequest.ProtoReflect.Descriptor instead.
func (*AllResourceServerRequest) Descriptor() ([]byte, []int) {
	return file_configure_resource_server_proto_rawDescGZIP(), []int{0}
}

func (x *AllResourceServerRequest) GetResourceId() uint32 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

type AllResourceServerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Server `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *AllResourceServerReply) Reset() {
	*x = AllResourceServerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configure_resource_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllResourceServerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllResourceServerReply) ProtoMessage() {}

func (x *AllResourceServerReply) ProtoReflect() protoreflect.Message {
	mi := &file_configure_resource_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllResourceServerReply.ProtoReflect.Descriptor instead.
func (*AllResourceServerReply) Descriptor() ([]byte, []int) {
	return file_configure_resource_server_proto_rawDescGZIP(), []int{1}
}

func (x *AllResourceServerReply) GetList() []*Server {
	if x != nil {
		return x.List
	}
	return nil
}

type PageServerResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId uint32 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Page     uint32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *PageServerResourceRequest) Reset() {
	*x = PageServerResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configure_resource_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageServerResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageServerResourceRequest) ProtoMessage() {}

func (x *PageServerResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configure_resource_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageServerResourceRequest.ProtoReflect.Descriptor instead.
func (*PageServerResourceRequest) Descriptor() ([]byte, []int) {
	return file_configure_resource_server_proto_rawDescGZIP(), []int{2}
}

func (x *PageServerResourceRequest) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *PageServerResourceRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageServerResourceRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PageServerResourceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint32      `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*Resource `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *PageServerResourceReply) Reset() {
	*x = PageServerResourceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configure_resource_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageServerResourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageServerResourceReply) ProtoMessage() {}

func (x *PageServerResourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_configure_resource_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageServerResourceReply.ProtoReflect.Descriptor instead.
func (*PageServerResourceReply) Descriptor() ([]byte, []int) {
	return file_configure_resource_server_proto_rawDescGZIP(), []int{3}
}

func (x *PageServerResourceReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageServerResourceReply) GetList() []*Resource {
	if x != nil {
		return x.List
	}
	return nil
}

var File_configure_resource_server_proto protoreflect.FileDescriptor

var file_configure_resource_server_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x1a, 0x17, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x18, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20,
	0x00, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x22, 0x3f, 0x0a,
	0x16, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x25, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x86,
	0x01, 0x0a, 0x19, 0x50, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x09,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12,
	0x26, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x2a, 0x04, 0x18, 0x14, 0x20, 0x00, 0x52, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x58, 0x0a, 0x17, 0x50, 0x61, 0x67, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x27, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_configure_resource_server_proto_rawDescOnce sync.Once
	file_configure_resource_server_proto_rawDescData = file_configure_resource_server_proto_rawDesc
)

func file_configure_resource_server_proto_rawDescGZIP() []byte {
	file_configure_resource_server_proto_rawDescOnce.Do(func() {
		file_configure_resource_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_configure_resource_server_proto_rawDescData)
	})
	return file_configure_resource_server_proto_rawDescData
}

var file_configure_resource_server_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_configure_resource_server_proto_goTypes = []interface{}{
	(*AllResourceServerRequest)(nil),  // 0: configure.AllResourceServerRequest
	(*AllResourceServerReply)(nil),    // 1: configure.AllResourceServerReply
	(*PageServerResourceRequest)(nil), // 2: configure.PageServerResourceRequest
	(*PageServerResourceReply)(nil),   // 3: configure.PageServerResourceReply
	(*Server)(nil),                    // 4: configure.Server
	(*Resource)(nil),                  // 5: configure.Resource
}
var file_configure_resource_server_proto_depIdxs = []int32{
	4, // 0: configure.AllResourceServerReply.list:type_name -> configure.Server
	5, // 1: configure.PageServerResourceReply.list:type_name -> configure.Resource
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_configure_resource_server_proto_init() }
func file_configure_resource_server_proto_init() {
	if File_configure_resource_server_proto != nil {
		return
	}
	file_configure_server_proto_init()
	file_configure_resource_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_configure_resource_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllResourceServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_configure_resource_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllResourceServerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_configure_resource_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageServerResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_configure_resource_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageServerResourceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_configure_resource_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_configure_resource_server_proto_goTypes,
		DependencyIndexes: file_configure_resource_server_proto_depIdxs,
		MessageInfos:      file_configure_resource_server_proto_msgTypes,
	}.Build()
	File_configure_resource_server_proto = out.File
	file_configure_resource_server_proto_rawDesc = nil
	file_configure_resource_server_proto_goTypes = nil
	file_configure_resource_server_proto_depIdxs = nil
}
