// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: configure_resource_server.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllResourceServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId int64 `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
}

func (x *AllResourceServerRequest) Reset() {
	*x = AllResourceServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configure_resource_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllResourceServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllResourceServerRequest) ProtoMessage() {}

func (x *AllResourceServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configure_resource_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllResourceServerRequest.ProtoReflect.Descriptor instead.
func (*AllResourceServerRequest) Descriptor() ([]byte, []int) {
	return file_configure_resource_server_proto_rawDescGZIP(), []int{0}
}

func (x *AllResourceServerRequest) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

type AllResourceServerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*AllResourceServerReply_ResourceServer `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *AllResourceServerReply) Reset() {
	*x = AllResourceServerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configure_resource_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllResourceServerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllResourceServerReply) ProtoMessage() {}

func (x *AllResourceServerReply) ProtoReflect() protoreflect.Message {
	mi := &file_configure_resource_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllResourceServerReply.ProtoReflect.Descriptor instead.
func (*AllResourceServerReply) Descriptor() ([]byte, []int) {
	return file_configure_resource_server_proto_rawDescGZIP(), []int{1}
}

func (x *AllResourceServerReply) GetList() []*AllResourceServerReply_ResourceServer {
	if x != nil {
		return x.List
	}
	return nil
}

type AllServerResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId int64 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *AllServerResourceRequest) Reset() {
	*x = AllServerResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configure_resource_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllServerResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllServerResourceRequest) ProtoMessage() {}

func (x *AllServerResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configure_resource_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllServerResourceRequest.ProtoReflect.Descriptor instead.
func (*AllServerResourceRequest) Descriptor() ([]byte, []int) {
	return file_configure_resource_server_proto_rawDescGZIP(), []int{2}
}

func (x *AllServerResourceRequest) GetServerId() int64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type AllServerResourceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*AllServerResourceReply_ResourceServer `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *AllServerResourceReply) Reset() {
	*x = AllServerResourceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configure_resource_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllServerResourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllServerResourceReply) ProtoMessage() {}

func (x *AllServerResourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_configure_resource_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllServerResourceReply.ProtoReflect.Descriptor instead.
func (*AllServerResourceReply) Descriptor() ([]byte, []int) {
	return file_configure_resource_server_proto_rawDescGZIP(), []int{3}
}

func (x *AllServerResourceReply) GetList() []*AllServerResourceReply_ResourceServer {
	if x != nil {
		return x.List
	}
	return nil
}

// 新增环境
type AddResourceServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId int64 `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ServerId   int64 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *AddResourceServerRequest) Reset() {
	*x = AddResourceServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configure_resource_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddResourceServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResourceServerRequest) ProtoMessage() {}

func (x *AddResourceServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configure_resource_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResourceServerRequest.ProtoReflect.Descriptor instead.
func (*AddResourceServerRequest) Descriptor() ([]byte, []int) {
	return file_configure_resource_server_proto_rawDescGZIP(), []int{4}
}

func (x *AddResourceServerRequest) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *AddResourceServerRequest) GetServerId() int64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

// 删除环境
type DeleteResourceServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteResourceServerRequest) Reset() {
	*x = DeleteResourceServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configure_resource_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResourceServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceServerRequest) ProtoMessage() {}

func (x *DeleteResourceServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configure_resource_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceServerRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceServerRequest) Descriptor() ([]byte, []int) {
	return file_configure_resource_server_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResourceServerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AllResourceServerReply_ResourceServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId int64   `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ServerId   int64   `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CreatedAt  int64   `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Server     *Server `protobuf:"bytes,4,opt,name=server,proto3" json:"server,omitempty"`
}

func (x *AllResourceServerReply_ResourceServer) Reset() {
	*x = AllResourceServerReply_ResourceServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configure_resource_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllResourceServerReply_ResourceServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllResourceServerReply_ResourceServer) ProtoMessage() {}

func (x *AllResourceServerReply_ResourceServer) ProtoReflect() protoreflect.Message {
	mi := &file_configure_resource_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllResourceServerReply_ResourceServer.ProtoReflect.Descriptor instead.
func (*AllResourceServerReply_ResourceServer) Descriptor() ([]byte, []int) {
	return file_configure_resource_server_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AllResourceServerReply_ResourceServer) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *AllResourceServerReply_ResourceServer) GetServerId() int64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *AllResourceServerReply_ResourceServer) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AllResourceServerReply_ResourceServer) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type AllServerResourceReply_ResourceServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId int64     `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ServerId   int64     `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Resource   *Resource `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *AllServerResourceReply_ResourceServer) Reset() {
	*x = AllServerResourceReply_ResourceServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configure_resource_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllServerResourceReply_ResourceServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllServerResourceReply_ResourceServer) ProtoMessage() {}

func (x *AllServerResourceReply_ResourceServer) ProtoReflect() protoreflect.Message {
	mi := &file_configure_resource_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllServerResourceReply_ResourceServer.ProtoReflect.Descriptor instead.
func (*AllServerResourceReply_ResourceServer) Descriptor() ([]byte, []int) {
	return file_configure_resource_server_proto_rawDescGZIP(), []int{3, 0}
}

func (x *AllServerResourceReply_ResourceServer) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *AllServerResourceReply_ResourceServer) GetServerId() int64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *AllServerResourceReply_ResourceServer) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

var File_configure_resource_server_proto protoreflect.FileDescriptor

var file_configure_resource_server_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x1a, 0x17, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x18, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20,
	0x00, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x22, 0xf9, 0x01,
	0x0a, 0x16, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x44, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x65, 0x2e, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x98,
	0x01, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x29,
	0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x40, 0x0a, 0x18, 0x41, 0x6c, 0x6c,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20,
	0x00, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0xdf, 0x01, 0x0a, 0x16,
	0x41, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x44, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65,
	0x2e, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x7f, 0x0a, 0x0e,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1f,
	0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x6a, 0x0a,
	0x18, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0b, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x1b, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x02, 0x69,
	0x64, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_configure_resource_server_proto_rawDescOnce sync.Once
	file_configure_resource_server_proto_rawDescData = file_configure_resource_server_proto_rawDesc
)

func file_configure_resource_server_proto_rawDescGZIP() []byte {
	file_configure_resource_server_proto_rawDescOnce.Do(func() {
		file_configure_resource_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_configure_resource_server_proto_rawDescData)
	})
	return file_configure_resource_server_proto_rawDescData
}

var file_configure_resource_server_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_configure_resource_server_proto_goTypes = []interface{}{
	(*AllResourceServerRequest)(nil),              // 0: configure.AllResourceServerRequest
	(*AllResourceServerReply)(nil),                // 1: configure.AllResourceServerReply
	(*AllServerResourceRequest)(nil),              // 2: configure.AllServerResourceRequest
	(*AllServerResourceReply)(nil),                // 3: configure.AllServerResourceReply
	(*AddResourceServerRequest)(nil),              // 4: configure.AddResourceServerRequest
	(*DeleteResourceServerRequest)(nil),           // 5: configure.DeleteResourceServerRequest
	(*AllResourceServerReply_ResourceServer)(nil), // 6: configure.AllResourceServerReply.ResourceServer
	(*AllServerResourceReply_ResourceServer)(nil), // 7: configure.AllServerResourceReply.ResourceServer
	(*Server)(nil),                                // 8: configure.Server
	(*Resource)(nil),                              // 9: configure.Resource
}
var file_configure_resource_server_proto_depIdxs = []int32{
	6, // 0: configure.AllResourceServerReply.list:type_name -> configure.AllResourceServerReply.ResourceServer
	7, // 1: configure.AllServerResourceReply.list:type_name -> configure.AllServerResourceReply.ResourceServer
	8, // 2: configure.AllResourceServerReply.ResourceServer.server:type_name -> configure.Server
	9, // 3: configure.AllServerResourceReply.ResourceServer.resource:type_name -> configure.Resource
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_configure_resource_server_proto_init() }
func file_configure_resource_server_proto_init() {
	if File_configure_resource_server_proto != nil {
		return
	}
	file_configure_server_proto_init()
	file_configure_resource_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_configure_resource_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllResourceServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_configure_resource_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllResourceServerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_configure_resource_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllServerResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_configure_resource_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllServerResourceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_configure_resource_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddResourceServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_configure_resource_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResourceServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_configure_resource_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllResourceServerReply_ResourceServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_configure_resource_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllServerResourceReply_ResourceServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_configure_resource_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_configure_resource_server_proto_goTypes,
		DependencyIndexes: file_configure_resource_server_proto_depIdxs,
		MessageInfos:      file_configure_resource_server_proto_msgTypes,
	}.Build()
	File_configure_resource_server_proto = out.File
	file_configure_resource_server_proto_rawDesc = nil
	file_configure_resource_server_proto_goTypes = nil
	file_configure_resource_server_proto_depIdxs = nil
}
