// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: configure_resource_value.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllResourceValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId uint32 `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
}

func (x *AllResourceValueRequest) Reset() {
	*x = AllResourceValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configure_resource_value_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllResourceValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllResourceValueRequest) ProtoMessage() {}

func (x *AllResourceValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configure_resource_value_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllResourceValueRequest.ProtoReflect.Descriptor instead.
func (*AllResourceValueRequest) Descriptor() ([]byte, []int) {
	return file_configure_resource_value_proto_rawDescGZIP(), []int{0}
}

func (x *AllResourceValueRequest) GetResourceId() uint32 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

type AllResourceValueReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*AllResourceValueReply_ResourceValue `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *AllResourceValueReply) Reset() {
	*x = AllResourceValueReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configure_resource_value_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllResourceValueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllResourceValueReply) ProtoMessage() {}

func (x *AllResourceValueReply) ProtoReflect() protoreflect.Message {
	mi := &file_configure_resource_value_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllResourceValueReply.ProtoReflect.Descriptor instead.
func (*AllResourceValueReply) Descriptor() ([]byte, []int) {
	return file_configure_resource_value_proto_rawDescGZIP(), []int{1}
}

func (x *AllResourceValueReply) GetList() []*AllResourceValueReply_ResourceValue {
	if x != nil {
		return x.List
	}
	return nil
}

// 修改资源值
type UpdateResourceValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId uint32                                      `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	List       []*UpdateResourceValueRequest_ResourceValue `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *UpdateResourceValueRequest) Reset() {
	*x = UpdateResourceValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configure_resource_value_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResourceValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceValueRequest) ProtoMessage() {}

func (x *UpdateResourceValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configure_resource_value_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceValueRequest.ProtoReflect.Descriptor instead.
func (*UpdateResourceValueRequest) Descriptor() ([]byte, []int) {
	return file_configure_resource_value_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateResourceValueRequest) GetResourceId() uint32 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *UpdateResourceValueRequest) GetList() []*UpdateResourceValueRequest_ResourceValue {
	if x != nil {
		return x.List
	}
	return nil
}

type AllResourceValueReply_ResourceValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EnvId      uint32 `protobuf:"varint,2,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	ResourceId uint32 `protobuf:"varint,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Value      string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt  uint32 `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *AllResourceValueReply_ResourceValue) Reset() {
	*x = AllResourceValueReply_ResourceValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configure_resource_value_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllResourceValueReply_ResourceValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllResourceValueReply_ResourceValue) ProtoMessage() {}

func (x *AllResourceValueReply_ResourceValue) ProtoReflect() protoreflect.Message {
	mi := &file_configure_resource_value_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllResourceValueReply_ResourceValue.ProtoReflect.Descriptor instead.
func (*AllResourceValueReply_ResourceValue) Descriptor() ([]byte, []int) {
	return file_configure_resource_value_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AllResourceValueReply_ResourceValue) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AllResourceValueReply_ResourceValue) GetEnvId() uint32 {
	if x != nil {
		return x.EnvId
	}
	return 0
}

func (x *AllResourceValueReply_ResourceValue) GetResourceId() uint32 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *AllResourceValueReply_ResourceValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AllResourceValueReply_ResourceValue) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type UpdateResourceValueRequest_ResourceValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnvId uint32 `protobuf:"varint,1,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UpdateResourceValueRequest_ResourceValue) Reset() {
	*x = UpdateResourceValueRequest_ResourceValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configure_resource_value_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResourceValueRequest_ResourceValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceValueRequest_ResourceValue) ProtoMessage() {}

func (x *UpdateResourceValueRequest_ResourceValue) ProtoReflect() protoreflect.Message {
	mi := &file_configure_resource_value_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceValueRequest_ResourceValue.ProtoReflect.Descriptor instead.
func (*UpdateResourceValueRequest_ResourceValue) Descriptor() ([]byte, []int) {
	return file_configure_resource_value_proto_rawDescGZIP(), []int{2, 0}
}

func (x *UpdateResourceValueRequest_ResourceValue) GetEnvId() uint32 {
	if x != nil {
		return x.EnvId
	}
	return 0
}

func (x *UpdateResourceValueRequest_ResourceValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_configure_resource_value_proto protoreflect.FileDescriptor

var file_configure_resource_value_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x1a, 0x17, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x5f,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x5f, 0x65, 0x6e, 0x76, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x17, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28,
	0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x0a, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x22, 0xea, 0x01, 0x0a, 0x15, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x42, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x2e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x2e, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x8c, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x6e, 0x76, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x65, 0x6e, 0x76, 0x49, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xdf, 0x01, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02,
	0x20, 0x00, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x47,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x4e, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x0a, 0x06, 0x65, 0x6e, 0x76, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20,
	0x00, 0x52, 0x05, 0x65, 0x6e, 0x76, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x07,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_configure_resource_value_proto_rawDescOnce sync.Once
	file_configure_resource_value_proto_rawDescData = file_configure_resource_value_proto_rawDesc
)

func file_configure_resource_value_proto_rawDescGZIP() []byte {
	file_configure_resource_value_proto_rawDescOnce.Do(func() {
		file_configure_resource_value_proto_rawDescData = protoimpl.X.CompressGZIP(file_configure_resource_value_proto_rawDescData)
	})
	return file_configure_resource_value_proto_rawDescData
}

var file_configure_resource_value_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_configure_resource_value_proto_goTypes = []interface{}{
	(*AllResourceValueRequest)(nil),                  // 0: configure.AllResourceValueRequest
	(*AllResourceValueReply)(nil),                    // 1: configure.AllResourceValueReply
	(*UpdateResourceValueRequest)(nil),               // 2: configure.UpdateResourceValueRequest
	(*AllResourceValueReply_ResourceValue)(nil),      // 3: configure.AllResourceValueReply.ResourceValue
	(*UpdateResourceValueRequest_ResourceValue)(nil), // 4: configure.UpdateResourceValueRequest.ResourceValue
}
var file_configure_resource_value_proto_depIdxs = []int32{
	3, // 0: configure.AllResourceValueReply.list:type_name -> configure.AllResourceValueReply.ResourceValue
	4, // 1: configure.UpdateResourceValueRequest.list:type_name -> configure.UpdateResourceValueRequest.ResourceValue
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_configure_resource_value_proto_init() }
func file_configure_resource_value_proto_init() {
	if File_configure_resource_value_proto != nil {
		return
	}
	file_configure_resource_proto_init()
	file_configure_env_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_configure_resource_value_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllResourceValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_configure_resource_value_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllResourceValueReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_configure_resource_value_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResourceValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_configure_resource_value_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllResourceValueReply_ResourceValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_configure_resource_value_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResourceValueRequest_ResourceValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_configure_resource_value_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_configure_resource_value_proto_goTypes,
		DependencyIndexes: file_configure_resource_value_proto_depIdxs,
		MessageInfos:      file_configure_resource_value_proto_msgTypes,
	}.Build()
	File_configure_resource_value_proto = out.File
	file_configure_resource_value_proto_rawDesc = nil
	file_configure_resource_value_proto_goTypes = nil
	file_configure_resource_value_proto_depIdxs = nil
}
