// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/limes-cloud/kratos/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsDatabase(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_Database.String() && e.Code == 200
}

func ErrorDatabaseFormat(format string, args ...interface{}) *errors.Error {
	return errors.New(200, ErrorReason_Database.String(), fmt.Sprintf(format, args...))
}

func ErrorDatabase() *errors.Error {
	return errors.New(200, ErrorReason_Database.String(), "数据库错误")
}

func IsTransform(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_Transform.String() && e.Code == 200
}

func ErrorTransformFormat(format string, args ...interface{}) *errors.Error {
	return errors.New(200, ErrorReason_Transform.String(), fmt.Sprintf(format, args...))
}

func ErrorTransform() *errors.Error {
	return errors.New(200, ErrorReason_Transform.String(), "数据转换失败")
}

func IsAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AlreadyExists.String() && e.Code == 200
}

func ErrorAlreadyExistsFormat(format string, args ...interface{}) *errors.Error {
	return errors.New(200, ErrorReason_AlreadyExists.String(), fmt.Sprintf(format, args...))
}

func ErrorAlreadyExists() *errors.Error {
	return errors.New(200, ErrorReason_AlreadyExists.String(), "数据已存在")
}

func IsParams(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_Params.String() && e.Code == 200
}

func ErrorParamsFormat(format string, args ...interface{}) *errors.Error {
	return errors.New(200, ErrorReason_Params.String(), fmt.Sprintf(format, args...))
}

func ErrorParams() *errors.Error {
	return errors.New(200, ErrorReason_Params.String(), "参数错误")
}

func IsNotRecord(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NotRecord.String() && e.Code == 200
}

func ErrorNotRecordFormat(format string, args ...interface{}) *errors.Error {
	return errors.New(200, ErrorReason_NotRecord.String(), fmt.Sprintf(format, args...))
}

func ErrorNotRecord() *errors.Error {
	return errors.New(200, ErrorReason_NotRecord.String(), "暂无数据记录")
}
